### ISSUE TITLE
车牌号中存在字母O和I不能过滤

### ISSUE THREAD

**Issue by duanjinqiu** [wujianqi/qi-validator#1]
![image](https://user-images.githubusercontent.com/28377146/80053263-10dc3900-854f-11ea-8eea-272cc424f018.png)

**Comment by wujianqi** [comment]
应该是0，不是O。参见国家标准GA36-2014，第十二页。https://wenku.baidu.com/view/4573909a964bcf84b9d57bc5.html
不存在O，I，除非假车牌。

**Comment by duanjinqiu** [comment]
如果用户手动输入车牌，把数字0输成字母O，验证方法无法把它过滤

------------------ 原始邮件 ------------------
发件人: wujianqi <notifications@github.com&gt;
发送时间: 2020年4月23日 18:11
收件人: wujianqi/qi-validator <qi-validator@noreply.github.com&gt;
抄送: duanjinqiu <471568720@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wujianqi/qi-validator] 车牌号中存在字母O和I不能过滤 (#1)

**Comment by wujianqi** [comment]
好，多谢提出，晚上修复更新。
